[package]
name = "clipment"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
dirs = "5.0.1"
eframe = "0.27.2"
egui = "0.27.2"
rfd = "0.14.1"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
sysinfo = "0.30.12"
tokio = "1.38.1"
